[build]
target = "wasm32-unknown-unknown"
rustc-wrapper = "sccache"

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

[target.wasm32-unknown-unknown]
# Optimize WASM builds for faster development
rustflags = ["-C", "opt-level=1"]

[env]
# Use fewer codegen units for faster builds (at cost of compile time)
CARGO_PROFILE_DEV_CODEGEN_UNITS = "1"

# Enable incremental compilation
CARGO_INCREMENTAL = "1"
