name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Disable sccache wrapper
        run: echo "RUSTC_WRAPPER=" >> $GITHUB_ENV

      - name: Build (native)
        run: cargo build --verbose

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Disable sccache wrapper
        run: echo "RUSTC_WRAPPER=" >> $GITHUB_ENV

      - name: Test (native)
        run: cargo test --verbose

  build-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - uses: Swatinem/rust-cache@v2

      - name: Disable sccache wrapper
        run: echo "RUSTC_WRAPPER=" >> $GITHUB_ENV

      - name: Install Trunk
        run: cargo install trunk --locked

      - name: Build WASM (Trunk)
        run: trunk build --release
