name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install sccache
        run: cargo install sccache

      - name: Install Trunk
        run: cargo install trunk

      - name: Add wasm32 target
        run: rustup target add wasm32-unknown-unknown

      - name: Build (native)
        run: cargo build --verbose

      - name: Test (native)
        run: cargo test --verbose

      - name: Build WASM (Trunk)
        run: trunk build --release
