name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Unset sccache wrapper
        run: echo "RUSTC_WRAPPER=" >> $GITHUB_ENV

      - name: Install Rust stable
        run: |
          rustup update stable
          rustup target add wasm32-unknown-unknown

      - name: Install Trunk
        run: cargo install trunk

      - name: Build WASM with Trunk
        run: trunk build --release
