name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Unset sccache wrapper
        run: echo "RUSTC_WRAPPER=" >> $GITHUB_ENV

      - name: Install Rust stable
        run: |
          rustup update stable
          rustup target add wasm32-unknown-unknown

      - name: Install cargo-binstall
        run: curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

      - name: Install Trunk
        run: cargo binstall trunk --no-confirm

      - name: Build WASM with Trunk
        run: trunk build --release
